# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "app".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose


version: "3.9"

services:
  postgres:               # <-- service name
    image: postgres:15    # <-- this must be indented under the service
    restart: always
    user: postgres
    environment:
      - POSTGRES_DB=bulk_email_db
      - POSTGRES_USER=bulk_user
      - POSTGRES_PASSWORD=bulkemail123
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "bulk_user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:




